### ISSUE TITLE
"npx create-abell-app ." not working, is this intensional or should we need to add this feature.

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/create-abell-app#16]
"npx create-abell-app ." not working, is this intensional or should we need to add this feature.
I don't have any other project with the same name. 

@saurabhdaware 

![Screenshot (286)](https://user-images.githubusercontent.com/43727167/101672468-e8706300-3a7b-11eb-8c82-b3676fd5280f.png)

_Originally posted by @saideepesh000 in https://github.com/abelljs/abell/discussions/103_

**Comment by saideepesh000** [comment]
@saurabhdaware, should I take up this.

**Comment by saurabhdaware** [comment]
https://github.com/abelljs/create-abell-app/blob/main/lib/actions.js#L102

So after this line, we can check if the directory that already exists is empty or not. If it is empty, then continue else stop the execution and throw error that the directory is not empty.

@saideepesh000

**Comment by saurabhdaware** [comment]
> @saurabhdaware, should I take up this.

Yes you can work on this. Thank you so much for reporting and picking this up :D

**Comment by saideepesh000** [comment]
@saurabhdaware, could you explain what's happening from this line.
 https://github.com/abelljs/create-abell-app/blob/ad65945ab5ef3aa8b6c644097c93d4e9fbb5d7fb/lib/utils.js#L49

**Comment by saideepesh000** [comment]
@saurabhdaware, I almost implemented the code but, when I'm trying to run it's showing the below error, empty is current empty folder. 
I passed path.resolve(process.cwd()); as "to"

" no such file or directory, copyfile 'E:\create-abell-app\templates\default\content\deployment\index.md' -> 'E:\empty\content\deployment\index.md'"
```
function copyFolderInCurrFolderSync(from, to, ignore = [], ignoreEmptyDirs = true) {
  if (ignore.includes(from)) {
    return;
  }
  const fromDirectories = fs.readdirSync(from);

  createPathIfAbsent(path.resolve(process.cwd()));
  fromDirectories.forEach((element) => {
    const fromElement = path.join(from, element);
    const toElement = path.join(to, element);
    if (fs.lstatSync(fromElement).isFile()) {
      if (!ignore.includes(fromElement)) {
        fs.copyFileSync(
          fromElement,
          toElement.replace(/gitignore/g, '.gitignore')
        );
      }
    } else {
      copyFolderInCurrFolderSync(fromElement, toElement, ignore);
      if (fs.existsSync(to) && ignoreEmptyDirs) {
        try {
          fs.rmdirSync(to);
        } catch (err) {
          if (err.code !== 'ENOTEMPTY') throw err;
        }
      }
    }
  });
}
```

**Comment by judicaelandria** [comment]
Hi @saideepesh000,
[https://github.com/abelljs/create-abell-app/blob/main/lib/actions.js#L102](https://github.com/abelljs/create-abell-app/blob/main/lib/actions.js#L102) after that line you make a condition to check if the directory or not if it's not empty you just log the error message in that line if empty you can follow the installation
here is a link to help [https://stackoverflow.com/questions/39217271/how-to-determine-whether-the-directory-is-empty-directory-with-nodejs](https://stackoverflow.com/questions/39217271/how-to-determine-whether-the-directory-is-empty-directory-with-nodejs), I hope it helped :)

**Comment by saurabhdaware** [comment]
Thanks for the help @judicaelandria.

You can drop a draft PR @saideepesh000 so that i will get to review the code and then we can make changes in it.

**Comment by saideepesh000** [comment]
Hey, @judicaelandria thanks for your help man. Hey, @saurabhdaware I am stuck with eslint errors, when committing it is running both prettier and eslint which is leading to indentation problems, how to fix this.

![Screenshot (287)](https://user-images.githubusercontent.com/43727167/102245551-b485b980-3f23-11eb-83b6-39b5512fb789.png)

**Comment by saurabhdaware** [comment]
Try running `npx eslint . --fix`

**Comment by saideepesh000** [comment]
> 
> 
> Try running `npx eslint . --fix`

No, this is not working, the indents are remaining as they were, is there any hack.

**Comment by saurabhdaware** [comment]
Try `npm run prettier` once. If that doesn't work, Do `git commit --no-verify` when committing. It will skip the hook and commit. We can fix it later.
