### ISSUE TITLE
Set directory name as a package name in package.json file

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/create-abell-app#7]
After `create-abell-app`, currently, the default name of the template is carried in the final app as well. Would be great if we could change the name in package.json with the directory name. `create-abell-app <directory-name>`

**Comment by PranjalAgni** [comment]
Can I work on this issue

**Comment by saurabhdaware** [comment]
Hi @PranjalAgni yes you can work on this

**Comment by saurabhdaware** [comment]
Let me know if you need any help. Thank you!

**Comment by PranjalAgni** [comment]
Can you please add the prettier configurations in the project going ahead, as my default formatter is currently being used and changes the styles. As of now I have disabled my default  formatter

**Comment by saurabhdaware** [comment]
Oh yes true. I will add it.
