### ISSUE TITLE
In local templates, always install latest minor version of abell.

### ISSUE THREAD

**Issue by saurabhdaware** [abelljs/create-abell-app#8]
Currently, there are 2 local templates, default and minimal. After `npm install` or `yarn`, the version of the abell mentioned in their package.json is installed.

But, with this, we have to update this repository on every Abell release. So we need a way to always install the latest minor version (As per the [SemVer](https://semver.org))

This is a little tricky since there isn't a straightforward command for this. 

These are the steps we will have to follow:
1. Read the current version from package.json (Let's say It is `2.5.66`)
2. Extract the major version (`2` in our case)
3. Plus 1 the value
4. Run `npm install abell@"<3.0.0"` (which installs the latest version before 3.0.0)

If there is any better way, do comment here.

**Comment by judicaelandria** [comment]
Hey @saurabhdaware,
I'll take this issue,
can you give detail and I'll work on it

**Comment by saurabhdaware** [comment]
First we have to check if the template asked is local or not. We can check it with 
```js
if (template === 'default' || template === 'minimal') {
}
```

If it is remote, then template will have value other than default or minimal.

When it is local, we can ignore the `npm install` or `yarn` command in,
https://github.com/abelljs/create-abell-app/blob/main/lib/actions.js#L84-L92

Else, We will read the abell's version from template's `package.json` file. And then perform,
> Read the current version from package.json (Let's say It is 2.5.66)
    Extract the major version (2 in our case)
    Plus 1 the value
    Run npm install abell@"<3.0.0" (which installs the latest version before 3.0.0)

If installer is yarn then we can use `yarn add abell@"<3.0.0"` instead I guess
